### PR TITLE
RHPAM-4271 minimist npm library to 1.2.6

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/RHPAM-4271

### CODE REVIEW

**Comment by yesamer** [comment]
Hi @Ginxo ! Please consider this repo is no longer actively maintained. This repo code has been moved here https://github.com/kiegroup/kie-tools.

**Review by yesamer — APPROVED** [review]
In any case, the change is fine - approving it.

**Comment by Ginxo** [comment]
thanks @yesamer up to you guys to merge.
should we archive this repository?

**Review by mareknovotny — APPROVED** [review]

**Comment by yesamer** [comment]
@Ginxo Yes, our intention was to archive this repo, when all PR were ported in the new one. This condition is now true, so I think we can proceed.

**Comment by mareknovotny** [comment]
ok @yesamer, please check the same and more dependtabot's alerts in the new one then

**Comment by yesamer** [comment]
@mareknovotny I don't have admin rights for https://github.com/kiegroup/kie-tools repo, but I think @ederign and @tiagobento are taking care of that repo alerts.

**Comment by Ginxo** [comment]
Merged. Repository archived and additional description `Archived repository. Please go to https://github.com/kiegroup/kie-tools` added to `About` info

**Pull request merged**
