### PR TITLE
Kogito-2528 : Reuse Data Types

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin this is the PR for the Reuse Data Types on this new fork. I cherry picked it and made several needed modications in order to be ok with the new project. Artifact can be found here. https://drive.google.com/drive/folders/14_toHacRbsz8hfpiNhH44YplSVcRhcYB?usp=sharing

### CODE REVIEW

**Comment by romartin** [comment]
@hasys please review needed here. Thanks!

**Review by hasys — APPROVED** [review]
Hi @inodeman,

great job, thank you! See testing results below. I guess we can report all found issues as separate issues if they wasn't reported before. I can report it, just let me know are they already reported or not. Thank you!

@romartin @inodeman I think PR is ready for merge after conflicts resolved and builds are green again. Thank you!

### Tested scenarios on VS Code extension:

- [x] Case file variables - wasn't tested since not present in VS Code extension
- [x] When a new custom data type is created the data type is visible on all places (datatype drop downs) within one process.
    - [x] Process variables
    - [x] Global variables
    - [x] Assignments
    - [x] Data Objects
    - [x] Imports
    - [x] Multiple Instance
- [ ] When a new custom data type is edited, the changes apply on all places within one process.
    - [x] Process variables
    - [x] Global variables
    - [x] Assignments
    - [x] Data Objects
    - [x] Imports
    - [x] Multiple Instance

### Found issues
1. You need to refresh forms to see new data type. Example: add new data type with global variable, check process variable datatypes
2. In **imports**, **Data Objects** and **MultiInstance** variables it is not possible to change previously created and selected Data Type. It is possible to edit newly created Data Type only. Example: create new Import Data Type. It is possible to edit this data type. Close Imports dialogue and open again - it is not possible to edit the data type anymore.
3. Everywhere except Assignments Data Types format of the new data type is "NewDataType [packge.of.the.new.type]", in the Assignments it is just "packge.of.the.new.type.NewDataType"

**Comment by romartin** [comment]
Ok, great job @hasys , thanks for the review and detailed feedback!! :+1: 

Hey @inodeman  - please could you fix the conflicts (by rebasing from msater) and fire builds again? Lemme know once this is ready to merge please. 

Thanks guys!!

**Comment by inodeman** [comment]
Hi @romartin rebased. New artifact here. https://drive.google.com/drive/folders/14_toHacRbsz8hfpiNhH44YplSVcRhcYB?usp=sharing

**Pull request merged**
