### PR TITLE
BXMSPROD-1558 using @kie/lock-treatment-tool

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1558

referenced pull requests:

* https://github.com/kiegroup/kogito-editors-java/pull/183
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1175
* https://github.com/kiegroup/lock-treatment-tool/pull/1
* https://github.com/kiegroup/lock-treatment-tool/pull/2
* https://github.com/kiegroup/kogito-editors-java/pull/183
* https://github.com/kiegroup/kogito-apps/pull/1139
* https://github.com/kiegroup/optaweb-employee-rostering/pull/729
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/612
* https://github.com/kiegroup/process-migration-service/pull/36

related to:

* https://github.com/kiegroup/kogito-editors-java/pull/172

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by yesamer** [comment]
It seems it's still failing :(

[2021-12-02T09:02:53.279Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npx (lock-treatment-tool execution) on project appformer-js-monaco: Failed to run task: 'npx @kie/lock-treatment-tool -- --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

[2021-12-02T09:02:53.279Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npx (lock-treatment-tool execution) on project kogito-editors-js: Failed to run task: 'npx @kie/lock-treatment-tool -- --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Review by yesamer — COMMENTED** [review]
It seems it's still failing :(

[2021-12-02T09:02:53.279Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npx (lock-treatment-tool execution) on project appformer-js-monaco: Failed to run task: 'npx @kie/lock-treatment-tool -- --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

[2021-12-02T09:02:53.279Z] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npx (lock-treatment-tool execution) on project kogito-editors-js: Failed to run task: 'npx @kie/lock-treatment-tool -- --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by Ginxo** [comment]
@yesamer thanks for checking it...
https://github.com/kiegroup/kie-jenkins-scripts/pull/1175 needs to be merged and slave images generated (I will do it) and then Jenkins's jobs will be relaunched

**Comment by Ginxo** [comment]
testing a new approach by https://github.com/kiegroup/kogito-editors-java/pull/184

**Comment by Ginxo** [comment]
replaced by https://github.com/kiegroup/kogito-editors-java/pull/184

**Pull request closed without merging**
