### PR TITLE
Bump version to `8.0.0-SNAPSHOT`

### PR DESCRIPTION
**Pull request by caponetto**

### CODE REVIEW

**Comment by tiagobento** [comment]
Hi @romartin @yesamer @karreiro! We're bumping the versions of the modules of this repo to 8.0.0-SNAPSHOT, so we don't clash with the BC stream. Please tell us if it's okay or if you'd like to use a different version.

**Comment by romartin** [comment]
Hey @tiagobento  @caponetto 

For me bumping to 8.x is ifne, although I need to clarify first how to keep working on our lienzo "new" versions on top of this repo.

As you know lienzo is still in a separate repo [1, 2], we're now trying to see if we can just these modules into this repository, this way all its stuff will follow same conventions and NPM, so build will be easier for everyone... anyway, on the MEANWHILE, we have to continue working with lienzo dependencies on this new repo, and we need to use a dfferent versions than the BC stream, is that possible right guys? Shouls we just change some pom here, in case we need to upgrade lienzo versions?

Thx!

[1] https://github.com/kiegroup/lienzo-core
[2] https://github.com/kiegroup/lienzo-tests

**Comment by tiagobento** [comment]
@romartin Right now Lienzo is being treated as an "external" dependency, so its version is fixed to 7.53.0.Final. As we spoke, you can create a new stream on Lienzo called 8.x and have this repo depend on Lienzo 8.0.0-SNAPSHOT or something like that. But generally, yeah, just change the POM files as you please :) A lot of this stuff is new, so we'll have to figure out a new workflow.

**Comment by romartin** [comment]
@tiagobento ok thanks for confirmation :) Makes sense to me.  I understand for now I can just override the version property for lienzo like done here: 
https://github.com/kiegroup/kogito-editors-java/blob/main/pom.xml#L161
and that's it right? at least for local...

Anyway I don't want to block this PR and this migration, I assume we can properly move forward with our tasks, so let's go ahead guys. Approving

**Comment by romartin** [comment]
@caponetto  @tiagobento I'm testing this PR locally.... will let you know ASAP

**Review by romartin — APPROVED** [review]
@caponetto @tiagobento thanks guys, great work agian!

I've tested locally command line builds, artifcats and SDM inside IntelliJ (java8), and everything ok for the BPMN side, also artifacts on 8.0 snapshot versions, so not conflicts with 7.x stream. 

I'll let other leads on DMN and SCESIM to also provide their feedback, but it's a great yes for me, thanks again for your hard work here :+1:

**Review by yesamer — APPROVED** [review]
Approved!

**Review by karreiro — APPROVED** [review]
Thank you, @caponetto 🚀

**Pull request merged**
