### PR TITLE
KOGITO-2313 - Support for node/events metadata attributes

### PR DESCRIPTION
**Pull request by Josephblt**
It is now possible to add metadata attributes to all nodes.

**JIRA**: [KOGITO-2313](https://issues.redhat.com/browse/KOGITO-2313)

**Referenced Pull Requests**:
https://github.com/kiegroup/kie-wb-common/pull/3659

**VS Code**: [VSCode Extension](https://drive.google.com/file/d/1vaKVwJOBjwzfxJgug98z9ZTCZiNWSidK/view?usp=sharing)

### CODE REVIEW

**Comment by domhanak** [comment]
Not sure why but there is something strange happening with tests for standalone editors. If it is possible could you please check if you can run them locally with these changes I won't be able to get to that earlier than next week..

**Comment by domhanak** [comment]
@Josephblt reviewed the code and I think we should add some unit tests for nodes that newly have advanced section. I think I went over all of the modified tests and did not notice new test cases, just mocks being fixed. Did I miss something?

Other than that is looks good.

Another question. Kinda offtopic, but this is touching its context, so I will ask :D
Would it be possible to add unqiue ID to global variables widget? They share the same widget as ProcessVariables and it makes it hard to find good locators for them in E2E tests.

**Review by domhanak — CHANGES_REQUESTED** [review]
Tested on VSCode, there are issues that need to be resolved before merge.

1. Adding metadata attribute Subprocess does not trigger dirty indicator and changes are not saved even when I explicitly press CTRL+S.
In order to reproduce just add Subprocess node and work with metadata attributes. Save & reopen to verify the expected work is preserved.

2. Every time I do SAVE operation on my process, close the editor and open it again. There are unexpected and duplicate metadata attributes added to `Activity` nodes. (Tasks, Subprocesses, CustomTasks)
In order to reproduce, just add an activity node to canvas. Save and reopen. The activity will contains metadata attribute `elementName={theActualName}` for Task it is `elementName=Task`. This repeats for each subsequent save in diagram.

Screenshot from 2021-06-16 11-29-14

**Comment by domhanak** [comment]
@Josephblt One more thing I noticed, which I do not think is related but I kind reproduce this on master.

Notice the quick menu being a bit more white when over different node:
Screenshot from 2021-06-16 12-04-43

On master I see this:
Screenshot from 2021-06-16 12-05-37

Any ideas why is this present here?

**Comment by romartin** [comment]
Hey @domhanak 

Thanks for the early feedback! 

I'm agree on the issues aronud new metadata widget about dirty state and saving/reopening, so plz @Josephblt could you verify and fix? Those look basic usecases we should properly handle. Thx in advance!

About the contextual menu appearance being changed, it's a recent update we just did, by collaborating with UX. See https://issues.redhat.com/browse/KOGITO-4977

Thanks!

**Comment by romartin** [comment]
@Josephblt any updates here?

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Hello @romartin, @domhanak. Yes. I fixed all issues here. Updated the PR and added the link with a .vsix for testing. You can go ahead with the testing.

**Comment by domhanak** [comment]
LGTM now I was unable to reproduce the issues found during 1st review. 
All nodes now include Advanced tab with metadata attributes table.

**Review by domhanak — APPROVED** [review]

**Review by romartin — APPROVED** [review]
Looks good to me as well! 

Thanks guys

**Comment by romartin** [comment]
@Josephblt hey could you please rerun the build to see the builds green? Once this is ready to merge, please let me know.
Thanks!

**Comment by Josephblt** [comment]
Jenkins do fdb

**Comment by romartin** [comment]
Hey @domhanak @ederign - you know if the CI integration tests are broken for this repo? Or this this specific PR which is causing issues during integration tests run? Looking at the generated errors, I looks not specific to these changes, and no way to make those work by re-firing jobs. Any ideas, and in case, is somebody is looking at this already? Thx in advance!

**Comment by ederign** [comment]
@karreiro can you help on this one tomorrow ?

**Comment by karreiro** [comment]
@ederign @romartin, the CI was passing for the latest merged PR [1] and it's still passing for [this PR](https://github.com/kiegroup/kogito-editors-java/pull/78) (still open), so I believe the CI integration tests are fine for the repo :-)

[1] Latest merged:
image

**Comment by domhanak** [comment]
@Josephblt it is safe to ignore the test failure in `kie-editors-standalone` we need to adjust the test to account for extra property row added by this PR.

**Comment by romartin** [comment]
Thanks @karreiro @domhanak for claritying.

@Josephblt  please rebase once possible, and I'll merge. 

Thanks guys!

**Comment by Josephblt** [comment]
Hello @romartin. Rebased. Let's wait for the builds now. Thanks.

**Comment by domhanak** [comment]
@kiegroup/gatekeepers This is good to be merged. Thank you!

**Pull request merged**
