### PR TITLE
KOGITO-5909: [DMN Designer] New Boxed Expression editor - DMN Expression column width is updated too many times in some scenarios

### PR DESCRIPTION
**Pull request by karreiro**
Jira: [KOGITO-5909](https://issues.redhat.com/browse/KOGITO-5909): [DMN Designer] New Boxed Expression editor - DMN Expression column width is updated too many times in some scenarios

**Before:**

**After:**

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
Great job, @karreiro

**Comment by danielzhe** [comment]
Hi, @karreiro ! Thanks for your PR! I found out that for "Decision Table" and "Relation" the call to `broadcastRelationExpressionDefinition` is happening two times, which cause issues with undo/redo since we have duplicated commands for those cases. Can you check it, please? Thank you!

**Comment by karreiro** [comment]
Thanks for the review, @danielzhe! I've not reproduced with the undo/redo feature, but I believe the issue is fixed now, see:

Before:
Kapture 2021-09-22 at 11 51 03

After:
Kapture 2021-09-22 at 11 49 12

Could you please take a look?

Thanks again 🚀  :-)

**Review by danielzhe — APPROVED** [review]
Great job! I didn't found any issue now! Thank you, @karreiro !

**Pull request merged**
