### PR TITLE
Kogito-5642: Fix blocker issues found by sonar

### PR DESCRIPTION
**Pull request by jomarko**
For more details see:
- https://issues.redhat.com/browse/KOGITO-5642

### CODE REVIEW

**Review by domhanak — APPROVED** [review]
Thank you @jomarko These changes seems like reasonable fixes. @romartin or @hasys could you please take a quick look?

**Comment by hasys** [comment]
Hi @jomarko good initiative, thank you!

However I am not sure in changes like:
* disable external entities access
* Unused public methods
* deprecated JsonFactory method

Close to the release date. Did you test those changes at runtime and sure they are safe?

**Comment by jomarko** [comment]
@hasys I will check these scenarios below, using produced vsix in this PR, feel free to add more you think should be checked

- [ ] create new, modify, save and reopen BPMN model
- [ ] open an old, modify, save and reopen BPMN model
- [ ] create new, modify, save and reopen DMN model
- [ ] open an old, modify, save and reopen DMN model

**Comment by romartin** [comment]
thanks @jomarko , it looks good to me

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
@romartin @hasys this is ready for merge now, if you do not have other comments. The sonar PR check activation will be done in a separate PR. This PR just fixes some most severe issues found by sonar.

**Review by hasys — APPROVED** [review]
Thank you @jomarko, looks good to me

**Comment by jomarko** [comment]
@romartin may I ask you for a merge?

**Comment by hasys** [comment]
@kiegroup/gatekeepers pr is ready for merge, thank you!

**Comment by ederign** [comment]
Please squash commits next time when merging it.

**Pull request merged**
