### PR TITLE
KOGITO-6449: [DMN Designer] Regression for setting name/dataType for BKM nodes, after KOGITO-4195

### PR DESCRIPTION
**Pull request by danielzhe**
I found out another issue during the development of this ticket, but it requires more time so I decided to create another ticket:
[Undo/Redo does not work for BKM nodes.](https://issues.redhat.com/browse/KOGITO-6474).

### CODE REVIEW

**Comment by danielzhe** [comment]
@vpellegrino FYI

**Comment by jomarko** [comment]
Should we review this PR or reopen for kogito-tooling once monorepo migration is done?

**Comment by yesamer** [comment]
@jomarko @danielzhe Considering Daniel is on PTO until next week, I don't see a reason to manage this PR in this repo. I suggest to ignore it, and wait to manage this in `kogito-tooling`

**Comment by danielzhe** [comment]
Thank you, guys! I'm closing this PR and creating a new one in monorep.

**Pull request closed without merging**
