### PR TITLE
KOGITO-4886: Remove the `errai-marshalling` module

### PR DESCRIPTION
**Pull request by caponetto**
- Remove the `errai-marshalling` module

- Remove some code from `EnvUtil.java` and `EnvironmentConfig.java` that was removed and then temporarily re-included in https://github.com/tiagobento/errai/pull/5 
@tiagobento can you please check these?

-  Remove the need for JSON conversion in `ActivityDataIOEditor.java` and `AssignmentsEditorWidget.java`
@romartin can you please check these?

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by romartin** [comment]
Hey @caponetto @tiagobento 

I know it's not a big change, but would like to double check the affected widget in bpmn still works, so could please upload the VSIX for quicly testing the UI? Or fire some job where I can test the result?

Thx in advance!

**Comment by caponetto** [comment]
Hi @romartin!
Our `CI :: Default` uploads the runtime war files once completed. See [here](https://github.com/kiegroup/kogito-editors-java/actions/runs/793466149) as an example.
I'm not sure if this is enough for validating this part so here is the [vsix file](https://www.dropbox.com/s/c4iljgiepha6x8d/KOGITO-4886.vsix?dl=0).
Thanks!

**Comment by romartin** [comment]
please @handreyrc can you help on the review for the BPMN affected widgets please? Thx!

**Review by handreyrc — APPROVED** [review]
Great Job @caponetto!
Everything working with the assignments.
Thanks
cc: @romartin

**Pull request merged**
