### PR TITLE
KOGITO-6323: Render DMN association waypoints

### PR DESCRIPTION
**Pull request by jomarko**
For more details see:
- https://issues.redhat.com/browse/KOGITO-6323

### CODE REVIEW

**Comment by jomarko** [comment]
tests are pending, will convert to regular PR once implemented

**Review by yesamer — APPROVED** [review]
LGTM

**Comment by jomarko** [comment]
@sthundat this is just a friendly reminder, if you have a time to review the PR.

**Comment by yesamer** [comment]
Jenkins retest this

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
sonar check job failed due to:
```
[2021-12-08T14:37:32.524Z] [INFO] boxed-expression-component: https://github.com/browserslist/browserslist#browsers-data-updating
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: ℹ ｢wds｣: Project is running at http://10.0.100.219/
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: ℹ ｢wds｣: webpack output is served from 
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: ℹ ｢wds｣: Content not from webpack is served from /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/packages/boxed-expression-component/showcase/public
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: ℹ ｢wds｣: 404s will fallback to /
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: Starting the development server...
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: node:events:342
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:       throw er; // Unhandled 'error' event
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:       ^
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/packages/boxed-expression-component/showcase/public'
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at Object.watch (node:fs:2240:34)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at createFsWatchInstance (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:38:15)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at setFsWatchListener (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:81:15)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:233:14)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher.NodeFsHandler._handleDir (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:429:19)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher.<anonymous> (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:477:19)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher.<anonymous> (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:482:16)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSReqCallback.oncomplete (node:fs:195:5)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: Emitted 'error' event on FSWatcher instance at:
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSWatcher._handleError (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/index.js:260:10)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at createFsWatchInstance (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:40:5)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at setFsWatchListener (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/chokidar/lib/nodefs-handler.js:81:15)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     [... lines matching original stack trace ...]
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at FSReqCallback.oncomplete (node:fs:195:5) {
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:   errno: -28,
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:   syscall: 'watch',
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:   code: 'ENOSPC',
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:   path: '/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/packages/boxed-expression-component/showcase/public',
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:   filename: '/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/packages/boxed-expression-component/showcase/public'
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: }
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: error Command failed with exit code 1.
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: Error: server closed unexpectedly
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at ChildProcess.onClose (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-editors-java.tests.kogito-tooling-editors-java/kogito-editors-java/kogito-editors-js/node_modules/start-server-and-test/src/index.js:75:14)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at ChildProcess.emit (node:events:365:28)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at maybeClose (node:internal/child_process:1067:16)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase:     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: error Command failed with exit code 1.
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: error Command failed with exit code 1.
[2021-12-08T14:37:54.683Z] [INFO] boxed-expression-component-showcase: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[2021-12-08T14:37:54.683Z] [INFO] lerna ERR! yarn run build:prod exited 1 in 'boxed-expression-component-showcase'
```

need to investigate if it is random or not

**Comment by jomarko** [comment]
fdb failed as:
```
2021-12-08T17:15:05.2720295Z @kogito-tooling/vscode-java-code-completion-extension-plugin: yarn run v1.22.10
2021-12-08T17:15:05.3371958Z @kogito-tooling/vscode-java-code-completion-extension-plugin: $ yarn lint && run-script-os
2021-12-08T17:15:05.5736023Z @kogito-tooling/vscode-java-code-completion-extension-plugin: $ echo 'Linting'
2021-12-08T17:15:05.5875156Z @kogito-tooling/vscode-java-code-completion-extension-plugin: Linting
2021-12-08T17:15:05.8579726Z @kogito-tooling/vscode-java-code-completion-extension-plugin: $ yarn install:mvnw && mvn clean install -B -ntp -DskipTests=$(build-env global.build.test --not)
2021-12-08T17:15:06.0903980Z @kogito-tooling/vscode-java-code-completion-extension-plugin: $ mvn -N io.takari:maven:wrapper -f ./
2021-12-08T17:15:07.3165347Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Scanning for projects...
2021-12-08T17:15:11.7909874Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [WARNING] The project io.github.kiegroup.kogito.tooling:vscode-java-code-completion-extension-plugin:pom:0.0.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
2021-12-08T17:15:11.8525785Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] 
2021-12-08T17:15:11.8529663Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] --< io.github.kiegroup.kogito.tooling:vscode-java-code-completion-extension-plugin >--
2021-12-08T17:15:11.8534606Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Building vscode-java-code-completion-extension-plugin :: parent 0.0.0
2021-12-08T17:15:11.8537028Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] --------------------------------[ pom ]---------------------------------
2021-12-08T17:15:11.8550538Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] 
2021-12-08T17:15:11.8554554Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] --- maven:0.7.7:wrapper (default-cli) @ vscode-java-code-completion-extension-plugin ---
2021-12-08T17:15:12.0219628Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] 
2021-12-08T17:15:12.0225760Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Maven Wrapper version 0.5.6 has been successfully set up for your project.
2021-12-08T17:15:12.0231235Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Using Apache Maven: 3.6.3
2021-12-08T17:15:12.0236928Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Repo URL in properties file: https://repo.maven.apache.org/maven2
2021-12-08T17:15:12.0244668Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] 
2021-12-08T17:15:12.0255654Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] ------------------------------------------------------------------------
2021-12-08T17:15:12.0262733Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] BUILD SUCCESS
2021-12-08T17:15:12.0270535Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] ------------------------------------------------------------------------
2021-12-08T17:15:12.0287090Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Total time:  4.737 s
2021-12-08T17:15:12.0299104Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Finished at: 2021-12-08T17:15:12Z
2021-12-08T17:15:12.0304377Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] ------------------------------------------------------------------------
2021-12-08T17:15:13.5003810Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Scanning for projects...
2021-12-08T17:15:15.5069662Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [WARNING] No explicit target runtime environment configuration. Build is platform dependent.
2021-12-08T17:15:20.2975005Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [INFO] Computing target platform for MavenProject: io.github.kiegroup.kogito.tooling:vscode-java-code-completion-extension-plugin-core:0.0.0 @ /home/runner/work/kogito-editors-java/kogito-editors-java/kogito-tooling/packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/pom.xml
2021-12-08T17:15:24.0225550Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] Failed to resolve target definition /home/runner/.m2/repository/org/eclipse/jdt/ls/org.eclipse.jdt.ls.tp/1.5.0.20211019160210/org.eclipse.jdt.ls.tp-1.5.0.20211019160210.target: Failed to load p2 metadata repository from location https://download.eclipse.org/eclipse/updates/4.22-I-builds/I20211010-1800/: No repository found at https://download.eclipse.org/eclipse/updates/4.22-I-builds/I20211010-1800. -> [Help 1]
2021-12-08T17:15:24.0233868Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] 
2021-12-08T17:15:24.0250250Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2021-12-08T17:15:24.0252578Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2021-12-08T17:15:24.0254256Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] 
2021-12-08T17:15:24.0256236Z @kogito-tooling/vscode-java-code-completion-extension-plugin: [ERROR] For more information about the errors and possible solutions, please read the following articles:
```

What is strange, as the same phas eon kogito-tooling passed on recent PRs - https://github.com/kiegroup/kogito-tooling/runs/4436834614?check_suite_focus=true

Will try just rerun

**Comment by adrielparedes** [comment]
The problem with vscode-java-code-completion-extension is not related to this PR. It's a problem with some eclipse dependencies versioning.

**Comment by yesamer** [comment]
Hello @sthundat, can you please finalize the review of this PR? Thx.

**Comment by jomarko** [comment]
This PR is replaced by:
- https://github.com/kiegroup/kogito-tooling/pull/748
- https://github.com/kiegroup/kogito-tooling/pull/749

**Pull request closed without merging**
