### PR TITLE
kie-parent version bump for 7.58.0.Final

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Review by karreiro — APPROVED** [review]
Thank you, @ederign!

**Review by romartin — APPROVED** [review]

**Comment by yesamer** [comment]
@ederign please wait until Tuesday, as I said I introduced some changes in the scesim api and I need to check it.

**Review by yesamer — APPROVED** [review]
@ederign @karreiro Approved.
Please consider merging https://github.com/kiegroup/kogito-editors-java/pull/97 after this, in order to keep synchronized API changes I introduced in drools repo.

**Review by yesamer — COMMENTED** [review]
Shouldn't we update the version on line 160 as well? @ederign

**Review by yesamer — CHANGES_REQUESTED** [review]
Shouldn't we update the version on line 160 as well? @ederign
https://github.com/kiegroup/kogito-editors-java/pull/93/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R160

**Comment by ederign** [comment]
@yesamer my bad! fixed! Thanks for spotting it

**Review by yesamer — APPROVED** [review]
@ederign Great, thx u. I approve the change, but I see a failing test on scesim side, this should be solved here https://github.com/kiegroup/kogito-editors-java/pull/97.

**Comment by karreiro** [comment]
@tiagobento Could you please take a look at this PR? :)

**Comment by tiagobento** [comment]
Changes look good to me. Ok to merge when green. We might need to rebase this PR after #97 .

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
