### PR TITLE
KOGITO-6181: Stunner-based editors are loosing focus when asked for the SVG

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR? As discussed, unselection is disabled for SVG, PNG, JPG and PDF

### CODE REVIEW

**Review by romartin — COMMENTED** [review]
Please @inodeman test try to select an element, and then export to svg:
- check the blue border, does it dissapear?
- check the toolbox, does it disspear?

**Comment by tiagobento** [comment]
@romartin @yesamer Hi guys! What's the status of this PR?

**Comment by romartin** [comment]
hey @tiagobento 

As far as I know @inodeman is checking if export goes well again, as it's supposed selected elements should stay after export, but the exported image should not contain the selection stuff (eg: toolbox).

Please @inodeman let us know when this PR is ready for review again, or if you have any concerns please ping me.

Thanks!

**Comment by inodeman** [comment]
Hi @tiagobento @romartin currently there are a couple of issues 1) It exports the toolbox 2) It selects the node in blue. See screenshot. I will let you know once it is fixed.
image

**Comment by inodeman** [comment]
Hi @LuboTerifaj ready for review again. You can find Vsix here. in VSCode you export SVG from Menu: View->Command Palette-> Type svg and select "Generate SVG without any notification". A couple of nodes. Currently the selected nodes are exported to SVG File, this is a side issue that was present before. We can file a new Jira for it if needed. Thanks, let me know

**Review by romartin — APPROVED** [review]
Thanks @inodeman , lookss good to me!!

**Comment by romartin** [comment]
Thanks @inodeman 

@LuboTerifaj as Jaime commented above, this PR just fixes the elements being unselected once exporting. PLEASE this is a blocker issue, can you please give it some priority? Release is tomorrow.... Thanks a lot in advance!

Also I created a new ticket and assigned to @inodeman , about the already existing issue once exporting, which does not removes the blue borders. See https://issues.redhat.com/browse/KOGITO-6271

Thanks guys!

**Comment by romartin** [comment]
Hey @inodeman could you please check the failed build, or upload some vsix otherwise, so @LuboTerifaj can go ahead with tests? Thanks!!

**Comment by inodeman** [comment]
Hi @romartin sorry seems the link did not paste before. Here it is https://drive.google.com/drive/folders/1G5UfG5aHqBHFX1RRYHErgnVNER9Felrw?usp=sharing

**Review by ederign — CHANGES_REQUESTED** [review]
As discussed on chat, I still lose focus even when I execute via command (on save).

The test failure is also related.

**Comment by jomarko** [comment]
I added myself as reviewer to check DMN once PR is ready, reading comments it seems it is not ready for review yet.

**Comment by inodeman** [comment]
Hi @ederign @jomarko @romartin please find Vsix for the build. I have tested it and to the best of my knowledge it complies with what we discussed on the call. Let me know. I will push changes shortly after I run all tests. https://drive.google.com/drive/folders/1G5UfG5aHqBHFX1RRYHErgnVNER9Felrw?usp=sharing

**Comment by inodeman** [comment]
Hi @romartin tested the scenarios you mentioned and to the best of my knowledge, it is ready for review. Thanks

**Review by jomarko — COMMENTED** [review]
I can confirm the selection is kept during generating a svg diagram for a DMN, however I am not sure about multiple DRDs in in DMN scenario. In such case a SVG for the current DRD is generated, is that an expected behavior @ederign ?

I can provide a DMN file for testing this if needed.

**Comment by romartin** [comment]
Hey @jomarko 

Thanks for the pointer. In fact, the export (svg, png, etc) just "exports" what is in the canvas itself, so if at some point the DRDs are visible, it will export those. On the other hand, ti's a good Q - what should be really exported?

Anyway I would say just to create a ticket for this, this is not a regression and we're not chaning any scope here, so it's something that we should discuss properly, out from scope from this work IMO.

**Review by romartin — APPROVED** [review]
Thanks @inodeman 

I've tested it and it works properly now. :+1:

**Review by jomarko — APPROVED** [review]
@romartin approving then

**Comment by romartin** [comment]
@LuboTerifaj @ederign 

Wanna git it a try? Artifacts are generated properly. Would be nice having your checks as well please :)

Thanks!

**Comment by LuboTerifaj** [comment]
Hello @romartin , @inodeman  thanks for the reminder, I am sorry but I was busy with other work as I already mentioned on our meeting. I will get to it this week. Thank you guys!

**Comment by LuboTerifaj** [comment]
Hello @inodeman , could you please have a look at my comment in the [KOGITO-6181](https://issues.redhat.com/browse/KOGITO-6181) jira? Thanks!

**Comment by inodeman** [comment]
Hi @LuboTerifaj added steps on Jira, let me know how it goes.

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @inodeman ,

first of all, my apologies for the late review, but I was occupied with higher priority tasks.

The svg file is now generated automatically. Is this expected behaviour? If yes, it should be specified also in jira.

Unfortunately I have also found a few issues:
- OnFocusChange save doesn't regenerate SVG immediately. I have reported it here: https://issues.redhat.com/browse/KOGITO-6495
- Generated SVG contains blue border on the node in case it was selected during generation. It is already reported here: https://issues.redhat.com/browse/KOGITO-6271
- When you are scrolling the canvas and the node is selected, the toolbox is moving as well.

The last issue mentioned above is significant and should be resolved in this PR.

Thank you!

**Comment by inodeman** [comment]
Hi @LuboTerifaj about the last issue reported, I did not change anything on the toolbox, I am pretty sure this bug also exists on main, so a new bug should be reported, let me know.

**Comment by LuboTerifaj** [comment]
Hello @inodeman , I cannot reproduce the issue in the latest BPMN editor release version (Kogito Bundle VSCode extension v0.15.0).

**Comment by inodeman** [comment]
Closed and reopened on new Repo

**Pull request closed without merging**
