### PR TITLE
KOGITO-5004 - Unable to view service tasks in VSCode if wid file has mavenDependencies tag

### PR DESCRIPTION
**Pull request by hasys**
JIRA: [KOGITO-5004](https://issues.redhat.com/browse/KOGITO-5004)

VS Code: [plugin](https://drive.google.com/file/d/1yDVHke4wk16vItFl2U-ZTT42yfvOmD1w/view?usp=sharing)

Hi @romartin, @domhanak, PR is ready for review. Thank you!

### CODE REVIEW

**Comment by domhanak** [comment]
@hasys Hey Kirill, thanks for the fix. I added ```"mavenDependencies": ["dependency"]``` and I can't see the task in palette. Is that expected?
On the other hand, the task has propert Icon, proper asssignments, name & properties so I just need to clarify the above.

**Comment by hasys** [comment]
Hi @domhanak, no it sounds like it doesn't work for you. I used for tests this WID file:

```
[
    [
        "name" : "firstWID",
        "parameters" : [
            "Incident" : new ObjectDataType()
        ]
        "mavenDependencies" : []
    ],

    [
        "name" : "secondWID",
        "results" : [
            "Result" : new ObjectDataType()
        ],
        "dependencies" : [""]
    ],

    [
        "mavenDependencies" : [
            "first",
            "second"
        ],
        "name" : "thirdWID"
    ],

    [
        "mavenDependencies" : ["dependency"],
        "name" : "fourthWID"
    ],


  [
    "name" : "MyTask", 
    "parameters" : [ 
        "MyFirstParam" : new StringDataType(), 
        "MySecondParam" : new StringDataType(), 
        "MyThirdParam" : new ObjectDataType() 
    ], 
    "results" : [ 
        "Result" : new ObjectDataType() 
    ], 
    "displayName" : "My Task", 
    "icon" : "",
    "customEditor" : "true",
    "displayName" : "My Task",
    "parameterValues" : [
       "MyFirstParam" : "A,B,C",   
       "MySecondParam" : "X,Y,Z"
    ],
    "defaultHandler" : "mvel: new DefaultHandler()",
    "mavenDependencies" : ["", "", "third"],
    "again" : [],
    "more" : ["list"]
  ],
  
  [
    "name" : "MyTask2", 
    "parameters" : [ 
        "MyFirstParam" : new StringDataType(), 
        "MySecondParam" : new StringDataType(), 
        "MyThirdParam" : new ObjectDataType() 
    ], 
    "results" : [ 
        "Result" : new ObjectDataType() 
    ], 
    "displayName" : "My Task 2", 
    "icon" : "" ,
    "list" : ["", "hello"]
  ]
]
```

And I can see all of them in the palette:
image

Please check that VSIX installed correct? I will check that attachments in this PR is correct as well.

Thank you!

**Comment by domhanak** [comment]
@hasys So it was my bad. Apologies, I did not notice I still had BPMN Editor installed. After I cleared my VSCode from old instances it worked well.

**Review by domhanak — APPROVED** [review]
LGTM.
I am unable to reproduce the issue with `mavenDepenencies` or any other MVEL list property that has strings in the list. Few examples I tested:
```
    "mavenDependencies" : ["Dependency:1.0.0"],
    "dependencies" : [],
    "customerCustomList" : ["1", "2", "3"]
```

There was one case where it got broken, but I think it is out of scope for this PR. @hasys please confirm.
`customList : [1, 2, 3]`

**Comment by hasys** [comment]
Good question @domhanak, I am not aware of use cases like this, so answer is yes it is out of scope of this PR. But if you know a valid use case for it, we can reconsider acceptance criteria.

Great job, thank you @domhanak!

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Hey @hasys 

Great, thanks!

**Comment by romartin** [comment]
jenkins retest this

**Comment by romartin** [comment]
oh sorry, refired the build but it's already green, just merging

**Pull request merged**
