### PR TITLE
KOGITO-5091 - creating connection can't be cancelled easily

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @domhanak, @jstastny-cz,

there is the fix. Issue was escape for actions wasn't migrated to Kogito hot keys API correctly. I migrated it and removed old parts of the API which is not in use anymore.

Fix works for both BPMN and DMN editors. I tested not only my fix but also all shortkeys from "Keyboard shortcuts" on my laptop, all works good.

[Tested VSIX](https://drive.google.com/file/d/1XmAHnDNhiu8cCTr0SVdCDav4yTpWHBOP/view?usp=sharing)

### CODE REVIEW

**Comment by jstastny-cz** [comment]
I'll leave code-reviews to others with deeper insight into the code-base. Just my personal opinion - the test removals seem to be fine with regards to refactoring made in this PR.

When testing the change using the attached vsix, I've encountered an issue with connector creation, see attached video. Is that a known issue or possibly a result of these changes?
connector-stuck

**Comment by hasys** [comment]
Hi @jstastny-cz, thank you for quick review.

Good catch, however issue is reproducible on the master branch as well so I guess it shouldn't block the PR. Thank you!

**Review by jstastny-cz — APPROVED** [review]
Thanks for clarification, otherwise works fine, thank you.

**Review by romartin — APPROVED** [review]
Thanks @hasys , looks good to me! Good refactor as well :+1:

**Comment by romartin** [comment]
Thanks @jstastny-cz , reported https://issues.redhat.com/browse/KOGITO-5600

**Pull request merged**
