### PR TITLE
KOGITO-5549 - WID files with comments and Imports can't be loaded

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @domhanak,

now it is possible to use comments (both single and multi line) and imports in WID files.

see [VS Code extension](https://drive.google.com/file/d/10tCqW6yruYsebGY9V-6JR88EMD6IGOcS/view?usp=sharing) for tests. Thank you!

### CODE REVIEW

**Comment by romartin** [comment]
Hey @hasys 

Code looks good. Although the PR title still talks "imports", but I think we're just supporting comments here. Is that correct? Can we change the title in that case to specify what's strictly fixed?

Thx in advance!

**Review by romartin — APPROVED** [review]
Forget my comment above please. I see we're just skipping everything before object starts, good point. Everything ok.
Thanks!

**Comment by domhanak** [comment]
Thanks I ll review tommorow

**Review by domhanak — APPROVED** [review]
LGTM

**Comment by domhanak** [comment]
@kiegroup/gatekeepers ready to be merged.

**Pull request merged**
