### PR TITLE
PF4 global styles wrapping

### PR DESCRIPTION
**Pull request by kelvah**
Hi @vpellegrino and @yesamer,
I've created this PR to showcase the PF styles wrapping using sass that we briefly discussed last week.
Let me know what you think.

### CODE REVIEW

**Comment by yesamer** [comment]
jenkins retest this please

**Review by yesamer — APPROVED** [review]
Thank you @kelvah for your contribution! LGTM!

**Comment by vpellegrino** [comment]
Hi @kelvah 
I checked out your branch and compiled the whole `kogito-editors-java` project.
Then, I launched `DMNKogitoTestingWebapp`, where the integration is in place.
It seems that the style is not applied:
image

@yesamer, did you try it? Is it something on my machine that is missing?

As soon as this PR is not in DRAFT status anymore, we need to involve @jomarko since he is the testing reference for this component.

In the meantime, thanks for your contribution @kelvah

**Comment by yesamer** [comment]
@vpellegrino I manually tested the generated `vsix` file by the FDB of the CI (https://github.com/kiegroup/kogito-editors-java/suites/4676836167/artifacts/127366753). Here it worked correctly. I didn't test `DMNKogitoTestingWebapp`, so good catch.

**Comment by kelvah** [comment]
hi @yesamer, @vpellegrino,

I did some tests with the dmn testing webapp and I've seen the style loading problem.
The same thing actually happens also when trying to test the online editor with this PR.

In order to make them work, the new wrapped style need to be imported by sass at build time (this is easily done by omitting the `.css` extension from the `@import` rule). But then new issues arise. The `base-no-reset` style from PF is also importing fonts with paths relative to PF folders. Even if we fix that, I would say that it's not responsibility of the `BoxedExpressionEditor`, or any similar component, to load PF fonts. We would also end up with duplicated loading anyway.

So, I think that relying on PF base styles "encapsulation" like I did it's not a great idea :/
I am inclined to close this PR.

Thank you for having a look at it.

**Comment by vpellegrino** [comment]
@kelvah, I appreciate that you gave a try to improve the styling organization of the component.
I remember I spent a few days solving the compatibility conflict issue and couldn't find a better solution.
Let's see during the following months if we can find something else.
Again, thanks for your contribution.

**Comment by yesamer** [comment]
Thank you for your tentative @kelvah

**Pull request closed without merging**
