### PR TITLE
KOGITO-6326: Regressions on LiteralExpression, after KOGITO-5078

### PR DESCRIPTION
**Pull request by ljmotta**
## JIRA
https://issues.redhat.com/browse/KOGITO-6326

I've added this temporary fix as it was [commented](https://github.com/kiegroup/kogito-editors-java/pull/159#discussion_r757647020) on #159, to have a proper fix it will be necessary to refactor a big part of the codebase.

I've created a new JIRA to track this refactor. https://issues.redhat.com/browse/KOGITO-6341

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by vpellegrino** [comment]
@ljmotta I just added a comment on https://issues.redhat.com/browse/KOGITO-6341
I think it is important to clarify that aspect before proceeding.
Furthermore, it would be nice to have an estimation of KOGITO-6341.

**Comment by ljmotta** [comment]
I've updated the JIRA with additional information. If it's necessary further clarification, please let me know.

**Review by jomarko — COMMENTED** [review]
@ljmotta thank you for a PR, we should add also tests I think. I prepared a test as https://github.com/ljmotta/kogito-editors-java/pull/1.

Please have a look on tests, possibly merge. Then once CI is green with new tests I can approve.

**Review by vpellegrino — APPROVED** [review]

**Comment by ljmotta** [comment]
@jomarko Thanks for preparing a test for it. I've merged it.

**Comment by jomarko** [comment]
@ljmotta I am sorry, it seems `husky` and `lint-staged` was skipped during my commit somehow, I guess I didn't run `yarn` to install husky before commit?

However may I ask you to fix formatting of the PR? Simply run `yarn format`

If you wish I do it, I can open another PR against your feature branch.

Thank you.

**Comment by ljmotta** [comment]
@jomarko No problem, I've pushed the formater fix.

**Review by jomarko — APPROVED** [review]

**Pull request merged**
