### PR TITLE
Test Scenario translations Updated

### PR DESCRIPTION
**Pull request by yesamer**
Based on https://github.com/kiegroup/drools-wb/pull/1490

### CODE REVIEW

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer! :-) I'm going to open a PR for DMN/BPMN soon :-)

**Comment by manstis** [comment]
@yesamer @karreiro You have to ask yourselves _why_ is this (are these) PR(s) necessary?

All i18n should be handled by the process @mbiarnes has setup. If files are being missed perhaps something else is wrong?

**Comment by karreiro** [comment]
@manstis yes, indeed :-) For this sync, I've created a PR for DMN/BPMN as well. But, I'm pinging @mbiarnes to understand why `kogito-editors-java` was not updated.

**Comment by yesamer** [comment]
@manstis I think nothing went wrong, most probably the process you mentioned didn't plan to update this repo, considering is a new repo. Of course, if @mbiarnes  prefers to update the process to include this repo, that is undoubtedly the best solution. No problem for me to close this PR if @mbiarnes wants to manage it.

**Comment by manstis** [comment]
@yesamer @karreiro @mbiarnes I suspect, as Guilherme said, this is a new repository and hence missed by the current process.

I am sure @mbiarnes would love nothing better than adding a new repository to the process ;-)

**Comment by karreiro** [comment]
@mbiarnes Could you please take a look when you have time? :-)

**Review by Rikkola — APPROVED** [review]
@mbiarnes is on PTO also we might have to ping him directly if he missed this. The PR itself is fine by me.

**Pull request merged**
