### PR TITLE
KOGITO-4818: Merge all the repos into a single repository keeping commit history

### PR DESCRIPTION
**Pull request by caponetto**
See: [KOGITO-4818](https://issues.redhat.com/browse/KOGITO-4818)

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Comment by ederign** [comment]
REMEMBER TO NOT SQUASH THIS TO PRESERVE THE HISTORY

**Review by tiagobento — APPROVED** [review]

**Review by romartin — APPROVED** [review]
Approving as we already did sanity checks for this stream. Thanks guys, great job!

**Review by karreiro — APPROVED** [review]
Thank you, @caponetto.

**Review by yesamer — APPROVED** [review]
Excellent work @caponetto

**Pull request merged**
