### PR TITLE
KOGITO-4765: Errors when executing models using imported inputs and/or decisions nodes - VS Code

### PR DESCRIPTION
**Pull request by yesamer**
**JIRA**: https://issues.redhat.com/browse/KOGITO-4765

These changes affect KOGITO only. BC has been managed in https://issues.redhat.com/browse/DROOLS-5844
 
 For a description of the PR, please refer to the one present here: https://github.com/kiegroup/drools-wb/pull/1446

To test it in Kogito, you can use the `Using Imported.scesim` asset, present in the related `kogito-runtimes` PR.

Related PRs:
* https://github.com/kiegroup/kogito-runtimes/pull/1349

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
I tried to build the VS Code Extension locally as the one built by jenkins doesn't seem to me contain latest pushed commits.

However I am not able to create a scesim file for a simple DMN, that uses imported InputData node.

Please notice my project structure in the screenshots and tell me if is that correct. In kogito-runtimes we put both dmn and scesim into `src/test/resources` what is a little bit suspicious.

Here is my DMN that simple increase the number by one:
Screenshot from 2021-07-19 11-43-25

And here is my scesim, but id doesn't offer me the imported InputData node.
Screenshot from 2021-07-19 11-43-36

**Comment by yesamer** [comment]
@jomarko Well, even decision "plus one" is missing, as results the test tools section is totally empty there. Can you please if you correctly saved the DMN file before creating the scesim one?

**Comment by yesamer** [comment]
@yesamer the sctructure is file, the only required constraint is to have `*.scesim` files under `/test/*` folder

**Comment by jomarko** [comment]
Screenshot from 2021-07-20 09-32-53

@yesamer after our discussion yesterday I am still unable to verify the PR. I did:
- `mvn clean install -DskipTests -Dgwt.compiler.skip` in `kogito-editors-java`
- `mvn clean install -DskipTests` in `kogito-editors-java/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime`
- `export EXTERNAL_RESOURCE_PATH__scesimEditor=/home/jomarko/redhat/github/kiegroup/kogito-editors-java/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulat` in `kogito-tooling`
- `yarn bootstrap` in `kogito-tooling`
- `yarn run build:prod` in `kogito-tooling`

However when trying to create or open any scesim file I am getting never ending loading screen as attached.

**Review by jomarko — APPROVED** [review]
Thank you @yesamer

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer!

**Pull request merged**
