### PR TITLE
KOGITO-5119: [DMN Designer] Add support for bend-points on connectors

### PR DESCRIPTION
**Pull request by danielzhe**

### CODE REVIEW

**Comment by danielzhe** [comment]
@karreiro @jomarko Ready for review.

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by karreiro — APPROVED** [review]
Excellent work, @danielzhe! Thank you :-)

**Review by jomarko — CHANGES_REQUESTED** [review]
@danielzhe thank you for this PR. It brings cool featrue. However I found an issue, that once a bend point is removed, the connected nodes can not be moved. See the video **not-able-to-move.webm** I have attached into jira.

**Comment by danielzhe** [comment]
Thank you for your review, @jomarko ! Looks like you found an issue that is affecting not only bend points in DMN but also in BPMN. I was able to reproduce and related issue in main branch on BPMN.
Steps do reproduce:
1. Add 2 nodes connected
2. Add a bend point and move it.
After that, all the diagram becomes "frozen" like in the video that you attached to JIRA. I think it may be related to this PR: https://github.com/kiegroup/kogito-editors-java/pull/63
I don't know if @romartin is aware of this issue.

**Review by jomarko — APPROVED** [review]
@danielzhe thank you. I reported these issues, that needs to be addressed separately.

- https://issues.redhat.com/browse/KOGITO-5594
- https://issues.redhat.com/browse/KOGITO-5595
- https://issues.redhat.com/browse/KOGITO-5596

**Comment by romartin** [comment]
thanks @danielzhe for reporting
Since the migration was merged, there are a few reported bugs about bendpoints, so we'll try to fix all at once asap.

**Pull request merged**
