### PR TITLE
KOGITO-4043: The nodes should be created on top of the selected node in DMN editor

### PR DESCRIPTION
**Pull request by danielzhe**
See: https://issues.redhat.com/browse/KOGITO-4043

### CODE REVIEW

**Comment by danielzhe** [comment]
jenkins do fdb

**Review by jomarko — COMMENTED** [review]
@danielzhe hello, thank you for the PR.

I found only one issue. It seems during computing a slot for new Decision/BKM node, we firstly check a free slot according to the axis X. What causes results described below. From my point of view they are not expected. What do you think please?

State before adding node
Screenshot from 2021-06-10 06-46-28

After node is added to InputData
Screenshot from 2021-06-10 06-46-43


I would expect Decision-4 to be vertically aligned with Decision-2

**Review by karreiro — COMMENTED** [review]
Thank you, @danielzhe. Great stuff!

@jomarko, thank you for the comment as well! While I understand the scenario you've highlighted seems a bit annoying. In this case, users are inverting the tree that we're trying to encourage, by using inputs living above of decisions. Still, I don't think we will be able to handle all possible scenarios. Let's see this example:

Screenshot 2021-06-11 at 11 58 16


In this case, we have many decision nodes at a lower level (considering "InputData-1" as the reference). In this kind of use case, only the business logic will help us to organize the diagram better.

Thus, I believe may stick with the simpler implementation that @danielzhe proposes, by creating the decisions always in the `RightUp` direction.

--

@danielzhe, I've notice an intermittent issue.

In the following gif we can see it buggy:

A

..but on this one we can see it working:

B


Wdyt?

Thanks again for this PR!

**Comment by danielzhe** [comment]
Thank you for the review, @karreiro ! About this issue, I noticed that if you drag the mouse a little bit (1 pixel is enough) after clicking on the "Create DMN Decision", it happens exactly what you reported. So for me it seems it is not an issue related to this PR. Can you confirm, please?

About what you found, @jomarko, I agree that it can be a bit annoying but as Guilherme mentioned, we trying to encourage users to create trees putting decisions above inputs, using a simple logic. Thank you for the review!

**Comment by karreiro** [comment]
@danielzhe I believe we may invest sometime to fix that issue, as I was able to frequently spot it locally :( 

Also, for some reason, I could not reproduce it on ~master~ main:

Kapture 2021-06-11 at 16 42 58

**Comment by jomarko** [comment]
@danielzhe @karreiro ok, thank you, then I think we need to resolve just the issue @karreiro is reporting https://github.com/kiegroup/kogito-editors-java/pull/58#issuecomment-859633435

**Comment by danielzhe** [comment]
Hi, @karreiro ! As we talked in private chat, I think this issue you reported is related to the speed of the click on the button and we are able to reproduce it on main even in BPMN. Let's wait now for @romartin review. Wdyt?

**Comment by danielzhe** [comment]
Here is the JIRA for the issue found by @karreiro : https://issues.redhat.com/browse/KOGITO-5328

**Review by karreiro — APPROVED** [review]
Thank you, @danielzhe.

**Review by jomarko — APPROVED** [review]
Thank you @danielzhe

**Review by romartin — APPROVED** [review]
Looks good to me as well, thanks @danielzhe !

**Comment by romartin** [comment]
@danielzhe @karreiro before merging, could someone double check BPMN works as before plz? I see some code updated on the core, although looks good at first glance, but would be nice having someone checking BPMN doesn't get broken. Also another option is assigning someone from QE to test it. Or if you push the vsix or war, I can also quickly test locallly.

**Comment by karreiro** [comment]
Thanks, @romartin! I just double-checked BPMN locally, and it's fine 🚀  (here's the [plugin](https://www.dropbox.com/s/sh8extec9826w98/KOGITO-4043.vsix?dl=0) in case you wanna double as well) :-)

**Comment by romartin** [comment]
@danielzhe @karreiro all good, go ahead guys , thanks!

**Pull request merged**
