### PR TITLE
KOGITO-5506 : BPMN Editor - Marshallers encoding issues

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin as discussed, removing calls to replaceIllegalChars, since gwt classes do that now. Can you review this PR?

### CODE REVIEW

**Comment by romartin** [comment]
Hey @inodeman 

Thanks for the fix, it looks good to me.

Although it's actually hard to know if we're breaking something by this change, as actually, on this kogito stream, we have not many marshalling tests (as we have in the "old" kie-wb-common )

So please, I think in order to ensure we don't break "marshallers" stuff, until we don't hve new marshallers and unit tests, it would be good idea "moving" these fixes to the "old" kie-wb-common stream, and execute all unit tests on that repo. As far I see the codebse for kie-wb-common and kogito, at marshallers level, should be similar, so I think it worths moving our latest fixees to the marshallers being done in this repo (so also including https://github.com/kiegroup/kogito-editors-java/pull/71 ) to the kie-wb-common side. This way we'll be able to execute all test case and ensure we don't break anything being tested before. If the fixes finally also make sene to include in kie-wb-common, even not requested by the ticket itself, we can also consider PRing there and fixing that repo.

WDYT?

**Comment by inodeman** [comment]
Hi @romartin, @domhanak I tested the issue on kie-wb-commons and the issue does not happen. Can you review this?

**Comment by romartin** [comment]
Thanks for the updates @inodeman 

Please @hasys , added you as the review for engineering as you're also up to date on these issues. Please sync with @domhanak and @inodeman to get this ready to merge.

Thanks guys!

**Review by hasys — CHANGES_REQUESTED** [review]
Hi @inodeman, I think issue not in the escaping some symbols, but that in some cases they are not escaping back.

I think we need to add `org.kie.workbench.common.stunner.core.util.StringUtils.revertIllegalCharsAttribute` method call there: https://github.com/kiegroup/kogito-editors-java/blob/80a34e97ae88541fcd884d76690f07fe11890479/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/activities/BaseCallActivityConverter.java#L56

Did you check it?

**Comment by inodeman** [comment]
> Hi @inodeman, I think issue not in the escaping some symbols, but that in some cases they are not escaping back.
> 
> I think we need to add `org.kie.workbench.common.stunner.core.util.StringUtils.revertIllegalCharsAttribute` method call there:
> 
> https://github.com/kiegroup/kogito-editors-java/blob/80a34e97ae88541fcd884d76690f07fe11890479/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/activities/BaseCallActivityConverter.java#L56
> 
> Did you check it?

Hi @hasys yes, I checked it. The issue is this. Our marshallers escape the text "Task & Char" to "Task &amp; Char" which is correct, the problem is that the XML saver from GWT then changes "Task &amp; Char" for "Task &amp;amp; Char" which is where the issue occurs, now when the diagram is loaded again, the characters are reverted so the text would be "Task &amp; Char" so it would appear that it did not revert illegal charecters but in fact it did.

**Comment by hasys** [comment]
Hi @inodeman, great finding, thank you! Just one more question, every `StringUtils.replaceIllegalChars` should have respective `StringUtils.revertIllegalCharsAttribute` calls as well. Why didn't it help? And should we remove it now after `StringUtils.replaceIllegalChars`  is removed?

**Comment by inodeman** [comment]
> Hi @inodeman, great finding, thank you! Just one more question, every `StringUtils.replaceIllegalChars` should have respective `StringUtils.revertIllegalCharsAttribute` calls as well. Why didn't it help? And should we remove it now after `StringUtils.replaceIllegalChars` is removed?

Hi @hasys you are right, I did some tests and seems the revert calls are not needed anymore.I will remove them

**Comment by inodeman** [comment]
Hi @romartin @hasys applied requested changes, can you re-review?

**Review by hasys — APPROVED** [review]
Great job, thank you @inodeman!

**Comment by domhanak** [comment]
Hello, checked the vscode extension and I can no longer reproduce the issue.

I used following process:
Screenshot from 2021-07-28 12-09-58


Special characters were not replaced when saved and reopened. :heavy_check_mark: 
Some examples for values in XML: (all other nodes are the same)
Value saved in XML `<drools:metaValue><![CDATA[Save & Test]]></drools:metaValue>` :heavy_check_mark: 
Value saved in XML `<drools:metaValue><![CDATA[end & error]]></drools:metaValue>` :heavy_check_mark: 
Vaue saved in XML `<drools:metaValue><![CDATA[Calculate %]]></drools:metaValue>` :heavy_check_mark: 

LGTM. Thanks

**Review by domhanak — APPROVED** [review]

**Comment by domhanak** [comment]
@kiegroup/gatekeepers ready for merging

**Pull request merged**
